// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_ZXZp9XIpjfc5aNnzrQxCkOyIiahjhY',
    appId: '1:649317535272:web:be8f233b0b7d9d8a34af1d',
    messagingSenderId: '649317535272',
    projectId: 'smartcampus-5e8fb',
    authDomain: 'smartcampus-5e8fb.firebaseapp.com',
    storageBucket: 'smartcampus-5e8fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdn8wmV0XhmoQPfwYGpAqQ-mSeslq--_I',
    appId: '1:649317535272:android:80ea9a66d8a700bd34af1d',
    messagingSenderId: '649317535272',
    projectId: 'smartcampus-5e8fb',
    storageBucket: 'smartcampus-5e8fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMcuhDg6FVPiK6gwn47TXkYEmQDWoLxqc',
    appId: '1:649317535272:ios:b6ab15fb13257fd534af1d',
    messagingSenderId: '649317535272',
    projectId: 'smartcampus-5e8fb',
    storageBucket: 'smartcampus-5e8fb.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMcuhDg6FVPiK6gwn47TXkYEmQDWoLxqc',
    appId: '1:649317535272:ios:b6ab15fb13257fd534af1d',
    messagingSenderId: '649317535272',
    projectId: 'smartcampus-5e8fb',
    storageBucket: 'smartcampus-5e8fb.firebasestorage.app',
    iosBundleId: 'com.example.smartcampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9_ZXZp9XIpjfc5aNnzrQxCkOyIiahjhY',
    appId: '1:649317535272:web:2bfd5931c39c2bfa34af1d',
    messagingSenderId: '649317535272',
    projectId: 'smartcampus-5e8fb',
    authDomain: 'smartcampus-5e8fb.firebaseapp.com',
    storageBucket: 'smartcampus-5e8fb.firebasestorage.app',
  );
}
